// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Question struct {
	ID            string           `json:"id"`
	QuizID        string           `json:"quiz_id"`
	QuestionText  string           `json:"question_text"`
	OptionA       string           `json:"option_a"`
	OptionB       string           `json:"option_b"`
	OptionC       string           `json:"option_c"`
	OptionD       string           `json:"option_d"`
	CorrectAnswer string           `json:"correct_answer"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Quiz struct {
	ID          string           `json:"id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type QuizAttempt struct {
	ID             string           `json:"id"`
	QuizID         string           `json:"quiz_id"`
	UserName       string           `json:"user_name"`
	Score          int32            `json:"score"`
	TotalQuestions int32            `json:"total_questions"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}
