// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error)
	CreateQuizAttempt(ctx context.Context, arg CreateQuizAttemptParams) (QuizAttempt, error)
	GetQuestionByID(ctx context.Context, id string) (Question, error)
	GetQuestionsByQuizID(ctx context.Context, quizID string) ([]GetQuestionsByQuizIDRow, error)
	GetQuizAttemptsByQuizID(ctx context.Context, quizID string) ([]QuizAttempt, error)
	GetQuizByID(ctx context.Context, id string) (Quiz, error)
	ListQuizzes(ctx context.Context) ([]Quiz, error)
}

var _ Querier = (*Queries)(nil)
